import {
  Import,
  Product,
  Supplier,
  VLXInspection,
  DashboardStats,
} from '@/types';

// ─── VLX Inspections ──────────────────────────────────────────────────────────

export const mockInspections: VLXInspection[] = [
  {
    id: 'vlx-001',
    title: 'Steel Mill Quality Audit - Baosteel Shanghai',
    inspectorName: 'James Chen',
    date: '2024-10-15',
    status: 'completed',
    score: 87,
    reportUrl: '#',
    findings: ['ISO 9001 compliance verified', 'Minor surface finish variance noted', 'Equipment calibration up to date'],
  },
  {
    id: 'vlx-002',
    title: 'Electronics Assembly Inspection - PCB Fab Taiwan',
    inspectorName: 'Sarah Kim',
    date: '2024-11-02',
    status: 'completed',
    score: 94,
    reportUrl: '#',
    findings: ['All IPC-A-610 standards met', 'Clean room protocols verified', 'RoHS documentation complete'],
  },
  {
    id: 'vlx-003',
    title: 'Textile Dye Process Audit - Vietnam Facility',
    inspectorName: 'Michael Torres',
    date: '2024-11-20',
    status: 'completed',
    score: 71,
    reportUrl: '#',
    findings: ['REACH compliance gaps identified', 'Wastewater treatment needs improvement', 'Labor standards met'],
  },
  {
    id: 'vlx-004',
    title: 'Final Assembly QC - Mexico Plant',
    inspectorName: 'Ana Gutierrez',
    date: '2024-12-01',
    status: 'completed',
    score: 91,
    reportUrl: '#',
    findings: ['Six Sigma quality process verified', 'Traceability barcoding confirmed', 'IMMEX compliance verified'],
  },
];

// ─── Suppliers ────────────────────────────────────────────────────────────────

export const mockSuppliers: Supplier[] = [
  {
    id: 'sup-001',
    name: 'Baosteel Shanghai Co., Ltd.',
    countryCode: 'CN',
    country: 'China',
    city: 'Shanghai',
    coordinates: { lat: 31.2304, lng: 121.4737, label: 'Baosteel Shanghai', country: 'China', countryCode: 'CN' },
    status: 'verified',
    ofacCheck: { checkedAt: '2024-12-01', status: 'clear' },
    capabilities: [
      { tag: 'Hot Rolling Mill', verified: true },
      { tag: 'Cold Rolling Mill', verified: true },
      { tag: 'ISO 9001 Certified', verified: true },
      { tag: 'Mill Test Reports (MTR)', verified: true },
      { tag: 'AS9100 Aerospace', verified: false },
    ],
    checks: [
      { category: 'OFAC/Sanctions', label: 'OFAC SDN List', status: 'pass' },
      { category: 'OFAC/Sanctions', label: 'BIS Entity List', status: 'pass' },
      { category: 'OFAC/Sanctions', label: 'UFLPA Entity List', status: 'pass' },
      { category: 'Legal', label: 'Business Registration Valid', status: 'pass' },
      { category: 'Legal', label: 'Export License (if req.)', status: 'pass' },
      { category: 'Legal', label: 'AD/CVD Affiliation Check', status: 'warn', notes: 'Steel products subject to AD/CVD review' },
      { category: 'Quality', label: 'ISO 9001 Certification', status: 'pass' },
      { category: 'Quality', label: 'MTR Issuance Capability', status: 'pass' },
      { category: 'Quality', label: 'Third-Party Inspection History', status: 'pass' },
      { category: 'ESG', label: 'Environmental Compliance', status: 'warn', notes: 'Carbon reporting partial' },
      { category: 'ESG', label: 'Labor Standards', status: 'pass' },
      { category: 'Financial', label: 'Financial Stability', status: 'pass' },
    ],
    score: 78,
    riskLevel: 'medium',
    documents: [
      { id: 'doc-s1', name: 'ISO_9001_Cert_2024.pdf', type: 'QUALITY_REPORT', fileUrl: '#', uploadedAt: '2024-01-15', size: '1.2 MB' },
      { id: 'doc-s2', name: 'Baosteel_MTR_Oct2024.pdf', type: 'MTR', fileUrl: '#', uploadedAt: '2024-10-20', size: '850 KB' },
    ],
    vlxInspectionIds: ['vlx-001'],
    createdAt: '2024-01-10',
    updatedAt: '2024-12-01',
  },
  {
    id: 'sup-002',
    name: 'Taiwan PCB Manufacturing Corp.',
    countryCode: 'TW',
    country: 'Taiwan',
    city: 'Hsinchu',
    coordinates: { lat: 24.8015, lng: 120.9718, label: 'Taiwan PCB Mfg', country: 'Taiwan', countryCode: 'TW' },
    status: 'verified',
    ofacCheck: { checkedAt: '2024-12-01', status: 'clear' },
    capabilities: [
      { tag: 'PCB Fabrication', verified: true },
      { tag: 'SMT Assembly', verified: true },
      { tag: 'IPC-A-610 Class 3', verified: true },
      { tag: 'RoHS Compliant', verified: true },
      { tag: 'ITAR Registered', verified: false },
    ],
    checks: [
      { category: 'OFAC/Sanctions', label: 'OFAC SDN List', status: 'pass' },
      { category: 'OFAC/Sanctions', label: 'BIS Entity List', status: 'pass' },
      { category: 'OFAC/Sanctions', label: 'UFLPA Entity List', status: 'pass' },
      { category: 'Legal', label: 'Business Registration Valid', status: 'pass' },
      { category: 'Legal', label: 'Export License (if req.)', status: 'pass' },
      { category: 'Legal', label: 'AD/CVD Affiliation Check', status: 'pass' },
      { category: 'Quality', label: 'IPC Certification', status: 'pass' },
      { category: 'Quality', label: 'RoHS Documentation', status: 'pass' },
      { category: 'Quality', label: 'Third-Party Inspection History', status: 'pass' },
      { category: 'ESG', label: 'Environmental Compliance', status: 'pass' },
      { category: 'ESG', label: 'Labor Standards', status: 'pass' },
      { category: 'Financial', label: 'Financial Stability', status: 'pass' },
    ],
    score: 94,
    riskLevel: 'low',
    documents: [
      { id: 'doc-s3', name: 'IPC_A610_Cert.pdf', type: 'QUALITY_REPORT', fileUrl: '#', uploadedAt: '2024-03-10', size: '2.1 MB' },
    ],
    vlxInspectionIds: ['vlx-002'],
    createdAt: '2023-06-15',
    updatedAt: '2024-12-01',
  },
  {
    id: 'sup-003',
    name: 'Hanoi Textile Group',
    countryCode: 'VN',
    country: 'Vietnam',
    city: 'Hanoi',
    coordinates: { lat: 21.0278, lng: 105.8342, label: 'Hanoi Textile Group', country: 'Vietnam', countryCode: 'VN' },
    status: 'flagged',
    ofacCheck: { checkedAt: '2024-12-01', status: 'clear' },
    capabilities: [
      { tag: 'Woven Fabric Production', verified: true },
      { tag: 'Dyeing & Finishing', verified: true },
      { tag: 'GOTS Certified', verified: false },
      { tag: 'OEKO-TEX Standard 100', verified: true },
    ],
    checks: [
      { category: 'OFAC/Sanctions', label: 'OFAC SDN List', status: 'pass' },
      { category: 'OFAC/Sanctions', label: 'BIS Entity List', status: 'pass' },
      { category: 'OFAC/Sanctions', label: 'UFLPA Entity List', status: 'pass' },
      { category: 'Legal', label: 'Business Registration Valid', status: 'pass' },
      { category: 'Legal', label: 'Export License (if req.)', status: 'pass' },
      { category: 'Legal', label: 'AD/CVD Affiliation Check', status: 'pass' },
      { category: 'Quality', label: 'GOTS Certification', status: 'fail', notes: 'Certification expired Jan 2024' },
      { category: 'Quality', label: 'OEKO-TEX Documentation', status: 'pass' },
      { category: 'Quality', label: 'Third-Party Inspection History', status: 'warn', notes: 'Flagged for REACH compliance gaps' },
      { category: 'ESG', label: 'Environmental Compliance', status: 'fail', notes: 'Wastewater treatment non-compliant' },
      { category: 'ESG', label: 'Labor Standards', status: 'pass' },
      { category: 'Financial', label: 'Financial Stability', status: 'pass' },
    ],
    score: 58,
    riskLevel: 'high',
    documents: [
      { id: 'doc-s4', name: 'OEKO_TEX_Cert.pdf', type: 'QUALITY_REPORT', fileUrl: '#', uploadedAt: '2024-06-01', size: '900 KB' },
    ],
    vlxInspectionIds: ['vlx-003'],
    createdAt: '2022-11-20',
    updatedAt: '2024-12-01',
  },
  {
    id: 'sup-004',
    name: 'Monterrey Assembly Solutions SA de CV',
    countryCode: 'MX',
    country: 'Mexico',
    city: 'Monterrey',
    coordinates: { lat: 25.6866, lng: -100.3161, label: 'Monterrey Assembly Solutions', country: 'Mexico', countryCode: 'MX' },
    status: 'verified',
    ofacCheck: { checkedAt: '2024-12-01', status: 'clear' },
    capabilities: [
      { tag: 'IMMEX Program', verified: true },
      { tag: 'Final Assembly', verified: true },
      { tag: 'Six Sigma Quality', verified: true },
      { tag: 'USMCA Rules of Origin', verified: true },
      { tag: 'ISO 14001 Environmental', verified: true },
    ],
    checks: [
      { category: 'OFAC/Sanctions', label: 'OFAC SDN List', status: 'pass' },
      { category: 'OFAC/Sanctions', label: 'BIS Entity List', status: 'pass' },
      { category: 'OFAC/Sanctions', label: 'UFLPA Entity List', status: 'pass' },
      { category: 'Legal', label: 'Business Registration Valid', status: 'pass' },
      { category: 'Legal', label: 'IMMEX Authorization', status: 'pass' },
      { category: 'Legal', label: 'AD/CVD Affiliation Check', status: 'pass' },
      { category: 'Quality', label: 'Six Sigma Certification', status: 'pass' },
      { category: 'Quality', label: 'Traceability System', status: 'pass' },
      { category: 'Quality', label: 'Third-Party Inspection History', status: 'pass' },
      { category: 'ESG', label: 'Environmental Compliance', status: 'pass' },
      { category: 'ESG', label: 'Labor Standards', status: 'pass' },
      { category: 'Financial', label: 'Financial Stability', status: 'pass' },
    ],
    score: 91,
    riskLevel: 'low',
    documents: [],
    vlxInspectionIds: ['vlx-004'],
    createdAt: '2021-03-01',
    updatedAt: '2024-12-01',
  },
];

// ─── Products ─────────────────────────────────────────────────────────────────

export const mockProducts: Product[] = [
  {
    id: 'prod-001',
    name: 'Industrial Control PCB Assembly',
    description: 'High-reliability printed circuit board assembly for industrial automation controllers',
    htsCode: {
      code: '8537.10.9170',
      description: 'Boards, panels, consoles: for a voltage not exceeding 1,000 V',
      dutyRate: '0%',
      adcvdCases: [],
      importsByCountry: [
        { countryCode: 'CN', country: 'China', value: '$2.1B' },
        { countryCode: 'TW', country: 'Taiwan', value: '$1.8B' },
        { countryCode: 'MX', country: 'Mexico', value: '$890M' },
      ],
    },
    skus: [
      { sku: 'PCB-IND-A100', quantity: 500, description: 'Rev A - Standard' },
      { sku: 'PCB-IND-A100-R', quantity: 200, description: 'Rev A - Ruggedized' },
      { sku: 'PCB-IND-B200', quantity: 300, description: 'Rev B - Enhanced' },
    ],
    components: [
      {
        id: 'comp-001',
        name: 'FR-4 PCB Substrate',
        type: 'substrate',
        htsCode: {
          code: '8534.00.0020',
          description: 'Printed circuits: multilayer',
          dutyRate: '0%',
          adcvdCases: [],
          importsByCountry: [{ countryCode: 'CN', country: 'China', value: '$4.2B' }],
        },
        supplierId: 'sup-002',
        supplierName: 'Taiwan PCB Manufacturing Corp.',
        country: 'Taiwan',
        countryCode: 'TW',
        coordinates: { lat: 24.8015, lng: 120.9718, label: 'Taiwan PCB Substrate', country: 'Taiwan', countryCode: 'TW' },
        quantity: 1000,
        unit: 'panels',
        documents: [
          { id: 'doc-c1', name: 'PCB_Substrate_Spec.pdf', type: 'TECHNICAL_DOC', fileUrl: '#', uploadedAt: '2024-09-10', size: '3.2 MB' },
        ],
        processes: [],
        riskLevel: 'low',
      },
      {
        id: 'comp-002',
        name: 'Steel Enclosure Bracket',
        type: 'component',
        htsCode: {
          code: '7326.90.8688',
          description: 'Other articles of iron or steel: other',
          dutyRate: '3.9%',
          adcvdCases: [
            {
              caseNumber: 'A-570-083',
              type: 'AD',
              country: 'China',
              countryCode: 'CN',
              rate: '25-250%',
              status: 'active',
              effectiveDate: '2016-07-27',
            },
          ],
          importsByCountry: [
            { countryCode: 'CN', country: 'China', value: '$1.1B' },
            { countryCode: 'TW', country: 'Taiwan', value: '$220M' },
          ],
        },
        supplierId: 'sup-001',
        supplierName: 'Baosteel Shanghai Co., Ltd.',
        country: 'China',
        countryCode: 'CN',
        coordinates: { lat: 31.2304, lng: 121.4737, label: 'Baosteel Shanghai', country: 'China', countryCode: 'CN' },
        quantity: 1000,
        unit: 'pieces',
        documents: [
          { id: 'doc-c2', name: 'MTR_Steel_Oct2024.pdf', type: 'MTR', fileUrl: '#', uploadedAt: '2024-10-22', size: '1.8 MB' },
        ],
        processes: [],
        riskLevel: 'medium',
      },
    ],
    processes: [
      {
        id: 'proc-001',
        name: 'PCB Fabrication & SMT Assembly',
        type: 'Manufacturing',
        supplierId: 'sup-002',
        supplierName: 'Taiwan PCB Manufacturing Corp.',
        country: 'Taiwan',
        countryCode: 'TW',
        coordinates: { lat: 24.8015, lng: 120.9718, label: 'PCB Fabrication - Taiwan', country: 'Taiwan', countryCode: 'TW' },
        startDate: '2024-10-01',
        endDate: '2024-10-25',
        status: 'verified',
        order: 1,
        documents: [
          { id: 'doc-p1', name: 'Assembly_Report_Oct2024.pdf', type: 'QUALITY_REPORT', fileUrl: '#', uploadedAt: '2024-10-28', size: '4.5 MB' },
        ],
        vlxInspectionId: 'vlx-002',
        notes: 'IPC-A-610 Class 3 assembly standard applied',
      },
      {
        id: 'proc-002',
        name: 'Steel Stamping & Forming',
        type: 'Manufacturing',
        supplierId: 'sup-001',
        supplierName: 'Baosteel Shanghai Co., Ltd.',
        country: 'China',
        countryCode: 'CN',
        coordinates: { lat: 31.2304, lng: 121.4737, label: 'Steel Stamping - Shanghai', country: 'China', countryCode: 'CN' },
        startDate: '2024-10-05',
        endDate: '2024-10-20',
        status: 'verified',
        order: 2,
        documents: [],
        vlxInspectionId: 'vlx-001',
      },
      {
        id: 'proc-003',
        name: 'Final Assembly & Test',
        type: 'Assembly',
        supplierId: 'sup-004',
        supplierName: 'Monterrey Assembly Solutions SA de CV',
        country: 'Mexico',
        countryCode: 'MX',
        coordinates: { lat: 25.6866, lng: -100.3161, label: 'Final Assembly - Monterrey', country: 'Mexico', countryCode: 'MX' },
        startDate: '2024-11-01',
        endDate: '2024-11-20',
        status: 'verified',
        order: 3,
        documents: [],
        vlxInspectionId: 'vlx-004',
        notes: 'USMCA qualification verified by customs broker',
      },
    ],
    finalAssemblyCountry: 'Mexico',
    finalAssemblyCountryCode: 'MX',
    finalAssemblyCoordinates: { lat: 25.6866, lng: -100.3161, label: 'Final Assembly - Monterrey', country: 'Mexico', countryCode: 'MX' },
    score: {
      overall: 84,
      originVerification: 91,
      supplierReliability: 82,
      processDocumentation: 88,
      complianceScore: 79,
      authenticity: 86,
      details: [
        'All component origins documented with supporting MTRs',
        'VLX inspections completed for all major processes',
        'AD/CVD exposure identified on steel components — review recommended',
        'USMCA qualification documented for final assembly',
        'Minor gap: Carbon footprint data incomplete for Chinese substrates',
      ],
    },
    status: 'verified',
    documents: [
      { id: 'doc-prod1', name: 'Commercial_Invoice_Nov2024.pdf', type: 'COMMERCIAL_INVOICE', fileUrl: '#', uploadedAt: '2024-11-25', size: '1.1 MB' },
      { id: 'doc-prod2', name: 'USMCA_COO_Nov2024.pdf', type: 'CERT_OF_ORIGIN', fileUrl: '#', uploadedAt: '2024-11-26', size: '780 KB' },
    ],
    vlxInspectionIds: ['vlx-002', 'vlx-004'],
    createdAt: '2024-09-01',
    updatedAt: '2024-12-01',
  },
  {
    id: 'prod-002',
    name: 'Technical Workwear Jacket',
    description: 'Hi-vis safety workwear jacket with reflective tape — EN ISO 20471 Class 3 certified',
    htsCode: {
      code: '6201.93.2010',
      description: 'Anoraks, windbreakers and similar articles: of man-made fibers',
      dutyRate: '27.7%',
      adcvdCases: [],
      importsByCountry: [
        { countryCode: 'VN', country: 'Vietnam', value: '$3.4B' },
        { countryCode: 'CN', country: 'China', value: '$2.9B' },
        { countryCode: 'BD', country: 'Bangladesh', value: '$1.1B' },
      ],
    },
    skus: [
      { sku: 'WW-JKT-S-HV', quantity: 1200, description: 'Small - Hi-Vis Yellow' },
      { sku: 'WW-JKT-M-HV', quantity: 2500, description: 'Medium - Hi-Vis Yellow' },
      { sku: 'WW-JKT-L-HV', quantity: 2000, description: 'Large - Hi-Vis Yellow' },
      { sku: 'WW-JKT-XL-HV', quantity: 1000, description: 'XL - Hi-Vis Yellow' },
    ],
    components: [
      {
        id: 'comp-003',
        name: 'Hi-Vis Woven Fabric (100% Polyester)',
        type: 'substrate',
        htsCode: {
          code: '5407.61.1100',
          description: 'Woven fabrics of synthetic filament yarn, 85% or more polyester',
          dutyRate: '14.9%',
          adcvdCases: [],
          importsByCountry: [
            { countryCode: 'CN', country: 'China', value: '$890M' },
            { countryCode: 'TW', country: 'Taiwan', value: '$340M' },
          ],
        },
        supplierId: 'sup-003',
        supplierName: 'Hanoi Textile Group',
        country: 'Vietnam',
        countryCode: 'VN',
        coordinates: { lat: 21.0278, lng: 105.8342, label: 'Hanoi Textile - Fabric', country: 'Vietnam', countryCode: 'VN' },
        quantity: 15000,
        unit: 'meters',
        documents: [],
        processes: [],
        riskLevel: 'high',
      },
    ],
    processes: [
      {
        id: 'proc-004',
        name: 'Fabric Dyeing & Finishing',
        type: 'Processing',
        supplierId: 'sup-003',
        supplierName: 'Hanoi Textile Group',
        country: 'Vietnam',
        countryCode: 'VN',
        coordinates: { lat: 21.0278, lng: 105.8342, label: 'Dyeing & Finishing - Hanoi', country: 'Vietnam', countryCode: 'VN' },
        startDate: '2024-09-15',
        endDate: '2024-10-10',
        status: 'flagged',
        order: 1,
        documents: [],
        vlxInspectionId: 'vlx-003',
        notes: 'REACH compliance gap identified — follow-up required',
      },
      {
        id: 'proc-005',
        name: 'Cut, Make, Trim (CMT)',
        type: 'Manufacturing',
        supplierId: 'sup-003',
        supplierName: 'Hanoi Textile Group',
        country: 'Vietnam',
        countryCode: 'VN',
        coordinates: { lat: 20.8449, lng: 106.6881, label: 'CMT - Haiphong', country: 'Vietnam', countryCode: 'VN' },
        startDate: '2024-10-12',
        endDate: '2024-11-01',
        status: 'verified',
        order: 2,
        documents: [],
      },
    ],
    finalAssemblyCountry: 'Vietnam',
    finalAssemblyCountryCode: 'VN',
    finalAssemblyCoordinates: { lat: 10.8231, lng: 106.6297, label: 'Final QC - Ho Chi Minh City', country: 'Vietnam', countryCode: 'VN' },
    score: {
      overall: 61,
      originVerification: 74,
      supplierReliability: 52,
      processDocumentation: 63,
      complianceScore: 58,
      authenticity: 72,
      details: [
        'REACH compliance gaps at dyeing facility — critical action required',
        'GOTS certification expired — supplier must renew',
        'Hi-vis fluorescence certification EN ISO 20471 on file',
        'VLX inspection flagged environmental non-compliance',
        'Country of origin well-documented; tariff classification verified',
      ],
    },
    status: 'flagged',
    documents: [
      { id: 'doc-prod3', name: 'EN_ISO_20471_Cert.pdf', type: 'QUALITY_REPORT', fileUrl: '#', uploadedAt: '2024-08-10', size: '1.5 MB' },
    ],
    vlxInspectionIds: ['vlx-003'],
    createdAt: '2024-07-15',
    updatedAt: '2024-12-01',
  },
];

// ─── Imports ──────────────────────────────────────────────────────────────────

export const mockImports: Import[] = [
  {
    id: 'imp-001',
    entryNumber: 'MIA-2024-8834721-3',
    entryType: 'Type 01 - Formal Consumption Entry',
    importerOfRecord: 'TechVault Industries LLC',
    portOfEntry: 'Port of Miami',
    portCode: 'MIA',
    entryDate: '2024-11-22',
    releaseDate: '2024-11-24',
    status: 'verified',
    products: [
      {
        productId: 'prod-001',
        productName: 'Industrial Control PCB Assembly',
        quantity: 1000,
        unit: 'units',
        value: 485000,
        currency: 'USD',
        countryOfOrigin: 'Mexico',
        countryOfOriginCode: 'MX',
        htsCode: '8537.10.9170',
        dutyRate: '0%',
        dutyPaid: 0,
      },
    ],
    totalDuties: 0,
    totalTariffs: 0,
    totalValue: 485000,
    currency: 'USD',
    bolNumber: 'MAEU324891020',
    vesselName: 'MSC OSCAR',
    voyageNumber: 'VY2411-08',
    countriesOfOrigin: ['Mexico'],
    documents: [
      { id: 'doc-imp1', name: 'BOL_MAEU324891020.pdf', type: 'BOL', fileUrl: '#', uploadedAt: '2024-11-20', size: '2.3 MB' },
      { id: 'doc-imp2', name: 'ISF_MIA20248834721.pdf', type: 'ISF', fileUrl: '#', uploadedAt: '2024-11-18', size: '780 KB' },
      { id: 'doc-imp3', name: 'Entry_7501_Nov2024.pdf', type: 'ENTRY_FORM', fileUrl: '#', uploadedAt: '2024-11-22', size: '1.1 MB' },
      { id: 'doc-imp4', name: 'CI_TechVault_Nov2024.pdf', type: 'COMMERCIAL_INVOICE', fileUrl: '#', uploadedAt: '2024-11-21', size: '920 KB' },
      { id: 'doc-imp5', name: 'USMCA_COO_Nov2024.pdf', type: 'CERT_OF_ORIGIN', fileUrl: '#', uploadedAt: '2024-11-22', size: '780 KB' },
    ],
    coordinates: [
      { lat: 24.8015, lng: 120.9718, label: 'PCB Sub-Assembly — Taiwan', country: 'Taiwan', countryCode: 'TW' },
      { lat: 31.2304, lng: 121.4737, label: 'Steel Components — Shanghai', country: 'China', countryCode: 'CN' },
      { lat: 25.6866, lng: -100.3161, label: 'Final Assembly — Monterrey', country: 'Mexico', countryCode: 'MX' },
      { lat: 25.7617, lng: -80.1918, label: 'Port of Entry — Miami', country: 'USA', countryCode: 'US' },
    ],
    notes: 'USMCA duty-free entry. Steel components from China subject to Section 232 tariff — IMMEX exclusion applied.',
  },
  {
    id: 'imp-002',
    entryNumber: 'LAX-2024-7219034-8',
    entryType: 'Type 01 - Formal Consumption Entry',
    importerOfRecord: 'SafeWork Supply Corp.',
    portOfEntry: 'Port of Long Beach',
    portCode: 'LGB',
    entryDate: '2024-11-28',
    releaseDate: '2024-12-02',
    status: 'flagged',
    products: [
      {
        productId: 'prod-002',
        productName: 'Technical Workwear Jacket',
        quantity: 6700,
        unit: 'units',
        value: 201000,
        currency: 'USD',
        countryOfOrigin: 'Vietnam',
        countryOfOriginCode: 'VN',
        htsCode: '6201.93.2010',
        dutyRate: '27.7%',
        dutyPaid: 55677,
      },
    ],
    totalDuties: 55677,
    totalTariffs: 55677,
    totalValue: 201000,
    currency: 'USD',
    bolNumber: 'HLCUSHA2411XXXXX',
    vesselName: 'CMA CGM MARCO POLO',
    voyageNumber: 'VY2411-14',
    countriesOfOrigin: ['Vietnam'],
    documents: [
      { id: 'doc-imp6', name: 'BOL_HLCUSHA2411.pdf', type: 'BOL', fileUrl: '#', uploadedAt: '2024-11-25', size: '1.9 MB' },
      { id: 'doc-imp7', name: 'ISF_LAX20247219034.pdf', type: 'ISF', fileUrl: '#', uploadedAt: '2024-11-23', size: '650 KB' },
      { id: 'doc-imp8', name: 'CI_SafeWork_Nov2024.pdf', type: 'COMMERCIAL_INVOICE', fileUrl: '#', uploadedAt: '2024-11-27', size: '840 KB' },
    ],
    coordinates: [
      { lat: 21.0278, lng: 105.8342, label: 'Fabric & Processing — Hanoi', country: 'Vietnam', countryCode: 'VN' },
      { lat: 10.8231, lng: 106.6297, label: 'Final QC & Packing — HCMC', country: 'Vietnam', countryCode: 'VN' },
      { lat: 33.7701, lng: -118.1937, label: 'Port of Entry — Long Beach', country: 'USA', countryCode: 'US' },
    ],
    notes: 'CBP flagged for REACH documentation review. Supplier compliance gaps noted in VLX inspection report vlx-003.',
  },
];

// ─── Dashboard Stats ──────────────────────────────────────────────────────────

export const mockDashboardStats: DashboardStats = {
  totalImports: 2,
  totalProducts: 2,
  totalSuppliers: 4,
  flaggedItems: 3,
  avgTraceabilityScore: 72.5,
  totalDutiesPaid: 55677,
  ofacFlags: 0,
  adcvdExposure: 1,
};
